#########################################################################
#									#
# Author: Copyright (C) 2026  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
#	AutoMake script file to run tests under make check.		#
#									#
#########################################################################


TESTS = ../prg/tests/test01.sh
TESTS += ../prg/tests/test01verbose.sh
TESTS += ../prg/tests/test02.sh
TESTS += ../prg/tests/test02verbose.sh
TESTS += ../prg/tests/test03.sh
TESTS += ../prg/tests/test03verbose.sh
TESTS += ../prg/tests/test04.sh
TESTS += ../prg/tests/test04verbose.sh
TESTS += ../prg/tests/test05.sh
TESTS += ../prg/tests/test05verbose.sh
TESTS += ../prg/tests/test06.sh
TESTS += ../prg/tests/test06verbose.sh
TESTS += ../tests/shellcheck/run-dot-sh-dot-in-pattern.sh
TESTS += ../tests/shellcheck/shellcheck-inline-dot-sh.sh

